Practical: Market Basket Analysis using Apriori Algorithm

1. Install Required Library

In [8]:
# pip install mlxtend

2. Import Libraries

In [9]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

3. Create Dataset

In [10]:
transactions = [
    ["Milk", "Bread"],
    ["Milk", "Bread", "Butter"],
    ["Bread", "Butter"],
    ["Milk", "Butter"],
    ["Bread", "Butter", "Eggs"],
    ["Milk", "Bread", "Eggs"],
    ["Milk", "Bread", "Butter", "Eggs"],
    ["Bread", "Eggs"],
    ["Milk", "Eggs"],
    ["Milk", "Butter", "Eggs"]
]

4. Transaction Encoding

In [11]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

print(df.head())

   Bread  Butter   Eggs   Milk
0   True   False  False   True
1   True    True  False   True
2   True    True  False  False
3  False    True  False   True
4   True    True   True  False

5. Apply Apriori Algorithm

In [12]:
frequent_itemsets = apriori(df, min_support=0.3, use_colnames=True)
frequent_itemsets

   support         itemsets
0      0.7          (Bread)
1      0.6         (Butter)
2      0.6           (Eggs)
3      0.7           (Milk)
4      0.4  (Bread, Butter)
5      0.4    (Bread, Eggs)
6      0.4    (Bread, Milk)
7      0.3   (Butter, Eggs)
8      0.4   (Butter, Milk)
9      0.4     (Milk, Eggs)

6. Generate Association Rules

In [13]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
rules = rules.sort_values(by="confidence", ascending=False)
rules

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

7. Output Frequent Itemsets and Rules

In [14]:
print("Frequent Itemsets:")
print(frequent_itemsets)

print("\nAssociation Rules:")
print(rules[["antecedents", "consequents", "support", "confidence", "lift"]])

Frequent Itemsets:
   support         itemsets
0      0.7          (Bread)
1      0.6         (Butter)
2      0.6           (Eggs)
3      0.7           (Milk)
4      0.4  (Bread, Butter)
5      0.4    (Bread, Eggs)
6      0.4    (Bread, Milk)
7      0.3   (Butter, Eggs)
8      0.4   (Butter, Milk)
9      0.4     (Milk, Eggs)

Association Rules:
Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

8. Interpretation

Frequent itemsets: Groups of items that occur together in transactions above the support threshold.

Association rules: Imply relationships between items, e.g., {Milk} → {Bread} means if a customer buys Milk, they are likely to buy Bread.