# Titanic Data Preprocessing

In this notebook, we will perform step-by-step preprocessing on the Titanic dataset:

1. Handling Missing Values  
2. Encoding Categorical Variables  
3. Scaling Numerical Features  
4. Creating New Features

## Step 1: Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

## Step 2: Load the Dataset

In [3]:
df = pd.read_csv("titanic.csv")
df

    Age  Gender  Fare Embarked  Siblings_Spouses
0  25.0    Male  15.5        S                 1
1  30.0  Female  22.0        C                 0
2   NaN    Male  18.2        S                 1
3  45.0  Female  50.0        Q                 2
4  33.0    Male  12.0        S                 0
5  22.0  Female   8.5        C                 0
6  50.0    Male  35.0        S                 1
7  60.0    Male  48.0        S                 1
8   NaN  Female  20.0      NaN                 0
9  29.0    Male  19.5        S                 0

## Step 3: Handling Missing Values

- **Age & Fare** → Fill with median (robust against outliers).  
- **Embarked** → Fill with most frequent value (mode).

In [4]:
# Check missing values
df.isnull().sum()
print("output \n",df)

# Impute median for numerical columns
imputer_median = SimpleImputer(strategy="median")
df[["Age", "Fare"]] = imputer_median.fit_transform(df[["Age", "Fare"]])

# Impute mode for categorical column
imputer_mode = SimpleImputer(strategy="most_frequent")
df[["Embarked"]] = imputer_mode.fit_transform(df[["Embarked"]])

df.isnull().sum()

output
     Age  Gender  Fare Embarked  Siblings_Spouses
0  25.0    Male  15.5        S                 1
1  30.0  Female  22.0        C                 0
2   NaN    Male  18.2        S                 1
3  45.0  Female  50.0        Q                 2
4  33.0    Male  12.0        S                 0
5  22.0  Female   8.5        C                 0
6  50.0    Male  35.0        S                 1
7  60.0    Male  48.0        S                 1
8   NaN  Female  20.0      NaN                 0
9  29.0    Male  19.5        S                 0

Age                 0
Gender              0
Fare                0
Embarked            0
Siblings_Spouses    0
dtype: int64

## Step 4: Encoding Categorical Variables

- **Gender** → Binary encoding (Male=0, Female=1).  
- **Embarked** → One-hot encoding for multiple categories.

In [5]:
# Encode Gender
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})

# One-Hot Encode Embarked
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)

df.head(10)

    Age  Gender  Fare  Siblings_Spouses  Embarked_Q  Embarked_S
0  25.0       0  15.5                 1       False        True
1  30.0       1  22.0                 0       False       False
2  31.5       0  18.2                 1       False        True
3  45.0       1  50.0                 2        True       False
4  33.0       0  12.0                 0       False        True
5  22.0       1   8.5                 0       False       False
6  50.0       0  35.0                 1       False        True
7  60.0       0  48.0                 1       False        True
8  31.5       1  20.0                 0       False        True
9  29.0       0  19.5                 0       False        True

## Step 5: Scaling Numerical Features

We scale the numerical features for better performance in ML models:
- Age  
- Fare  
- Siblings_Spouses

In [6]:
scaler = StandardScaler()
num_features = ["Age", "Fare", "Siblings_Spouses"]

df[num_features] = scaler.fit_transform(df[num_features])
df.head(10)

        Age  Gender      Fare  Siblings_Spouses  Embarked_Q  Embarked_S
0 -0.937155       0 -0.680520          0.603023       False        True
1 -0.499232       1 -0.208441         -0.904534       False       False
2 -0.367855       0 -0.484426          0.603023       False        True
3  0.814537       1  1.825130          2.110579        True       False
4 -0.236478       0 -0.934716         -0.904534       False        True
5 -1.199909       1 -1.188913         -0.904534       False       False
6  1.252460       0  0.735717          0.603023       False        True
7  2.128306       0  1.679875          0.603023       False        True
8 -0.367855       1 -0.353696         -0.904534       False        True
9 -0.586817       0 -0.390010         -0.904534       False        True

## Step 6: Creating New Features

We engineer new features to add more information:
- **Family_Size** = Siblings/Spouses + Self  
- **Age_Group** = Age bins (Child, Young, Adult, Senior)

In [7]:
# Family size feature
df["Family_Size"] = df["Siblings_Spouses"] + 1

# Age group feature
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[-np.inf, -0.5, 0.5, 1.5, np.inf],
    labels=["Child", "Young", "Adult", "Senior"]
)

df.head(10)

,Age,Gender,Fare,Siblings_Spouses,Embarked_Q,Embarked_S,Family_Size,Age_Group
0,-0.937155,0,-0.680520,0.603023,False,True,1.603023,Child
1,-0.499232,1,-0.208441,-0.904534,False,False,0.095466,Young
2,-0.367855,0,-0.484426,0.603023,False,True,1.603023,Young
3,0.814537,1,1.825130,2.110579,True,False,3.110579,Adult
4,-0.236478,0,-0.934716,-0.904534,False,True,0.095466,Young
5,-1.199909,1,-1.188913,-0.904534,False,False,0.095466,Child
6,1.252460,0,0.735717,0.603023,False,True,1.603023,Adult
7,2.128306,0,1.679875,0.603023,False,True,1.603023,Senior
8,-0.367855,1,-0.353696,-0.904534,False,True,0.095466,Young
9,-0.586817,0,-0.390010,-0.904534,False,True,0.095466,Child

## Step 7: Compare Original Data vs Final Preprocessed Output

In [8]:
# Reload original dataset to compare
df_original = pd.read_csv("titanic.csv")

print("🔹 Original Titanic Data (with NaN values):")
display(df_original.head(10))

print("\n✅ Final Titanic Data Preprocessing Completed:")
display(df.head(10))

🔹 Original Titanic Data (with NaN values):

    Age  Gender  Fare Embarked  Siblings_Spouses
0  25.0    Male  15.5        S                 1
1  30.0  Female  22.0        C                 0
2   NaN    Male  18.2        S                 1
3  45.0  Female  50.0        Q                 2
4  33.0    Male  12.0        S                 0
5  22.0  Female   8.5        C                 0
6  50.0    Male  35.0        S                 1
7  60.0    Male  48.0        S                 1
8   NaN  Female  20.0      NaN                 0
9  29.0    Male  19.5        S                 0

✅ Final Titanic Data Preprocessing Completed:

,Age,Gender,Fare,Siblings_Spouses,Embarked_Q,Embarked_S,Family_Size,Age_Group
0,-0.937155,0,-0.680520,0.603023,False,True,1.603023,Child
1,-0.499232,1,-0.208441,-0.904534,False,False,0.095466,Young
2,-0.367855,0,-0.484426,0.603023,False,True,1.603023,Young
3,0.814537,1,1.825130,2.110579,True,False,3.110579,Adult
4,-0.236478,0,-0.934716,-0.904534,False,True,0.095466,Young
5,-1.199909,1,-1.188913,-0.904534,False,False,0.095466,Child
6,1.252460,0,0.735717,0.603023,False,True,1.603023,Adult
7,2.128306,0,1.679875,0.603023,False,True,1.603023,Senior
8,-0.367855,1,-0.353696,-0.904534,False,True,0.095466,Young
9,-0.586817,0,-0.390010,-0.904534,False,True,0.095466,Child

## ✅ Final Output

In [9]:
print("Titanic Data Preprocessing Completed ✅")
df.head(10)

Titanic Data Preprocessing Completed ✅

,Age,Gender,Fare,Siblings_Spouses,Embarked_Q,Embarked_S,Family_Size,Age_Group
0,-0.937155,0,-0.680520,0.603023,False,True,1.603023,Child
1,-0.499232,1,-0.208441,-0.904534,False,False,0.095466,Young
2,-0.367855,0,-0.484426,0.603023,False,True,1.603023,Young
3,0.814537,1,1.825130,2.110579,True,False,3.110579,Adult
4,-0.236478,0,-0.934716,-0.904534,False,True,0.095466,Young
5,-1.199909,1,-1.188913,-0.904534,False,False,0.095466,Child
6,1.252460,0,0.735717,0.603023,False,True,1.603023,Adult
7,2.128306,0,1.679875,0.603023,False,True,1.603023,Senior
8,-0.367855,1,-0.353696,-0.904534,False,True,0.095466,Young
9,-0.586817,0,-0.390010,-0.904534,False,True,0.095466,Child

# 📌 Summary
- Missing values handled with Median & Mode  
- Categorical variables encoded (Gender + Embarked)  
- Features scaled using StandardScaler  
- New features created: Family_Size, Age_Group  


created by @keyurbhatiya